### PR TITLE
Changes for readr 1.3 behavior

### PR DESCRIPTION
**Pull request by bpbond**
Corresponds to `gcamdata` PR https://github.com/JGCRI/gcamdata/pull/1073.

@pralitp These changes to `gcamdata.compdata` are almost all changes from character to logical, or integer to numeric, so that `gcamdata` tests correctly with new `readr` 1.3.1. See [this comment below](
https://github.com/JGCRI/gcamdata.compdata/pull/22#issuecomment-450723231) for two very small numerical adjustments.

### CODE REVIEW

**Comment by bpbond** [comment]
## L100.FAO_CL_kha

For L100.FAO_CL_kha, the old and new dataframes are the same; it's the different types (caused by `readr` behavior change) that is causing failure:

```R
test_oldnew.R:112: failure: matches old data system output
as.data.frame(round_df(olddata)) not equivalent to as.data.frame(round_df(newdata)).
Component "value": Mean relative difference: 2.250843e-06
L100.FAO_CL_kha.csv doesn't match

> old <- COMPDATA$L100.FAO_CL_kha
> new <- readr::read_csv("outputs/L100.FAO_CL_kha.csv", comment="#")
> old
# A tibble: 8,960 x 9
   countries   country.codes item  item.codes element element.codes iso    year  value
   <chr>               <int> <chr>      <int> <chr>           <int> <chr> <int>  <dbl>
 1 Afghanistan             2 Arab…       6621 CL_kha             11 afg    1971 7.89e3
 2 Albania                 3 Arab…       6621 CL_kha             11 alb    1971 5.30e2
 3 Algeria                 4 Arab…       6621 CL_kha             11 dza    1971 6.38e3
 4 American S…             5 Arab…       6621 CL_kha             11 asm    1971 1.00e0
 5 Andorra                 6 Arab…       6621 CL_kha             11 and    1971 1.00e0
 6 Angola                  7 Arab…       6621 CL_kha             11 ago    1971 2.90e3
 7 Antigua an…             8 Arab…       6621 CL_kha             11 atg    1971 5.80e0
 8 Argentina               9 Arab…       6621 CL_kha             11 arg    1971 2.60e4
 9 Aruba                  22 Arab…       6621 CL_kha             11 abw    1971 2.00e0
10 Australia              10 Arab…       6621 CL_kha             11 aus    1971 4.10e4
# ... with 8,950 more rows
> new
# A tibble: 8,960 x 9
   countries   country.codes item  item.codes element element.codes iso    year  value
   <chr>               <dbl> <chr>      <dbl> <chr>           <dbl> <chr> <dbl>  <dbl>
 1 Afghanistan             2 Arab…       6621 CL_kha             11 afg    1971 7.89e3
 2 Albania                 3 Arab…       6621 CL_kha             11 alb    1971 5.30e2
 3 Algeria                 4 Arab…       6621 CL_kha             11 dza    1971 6.38e3
 4 American S…             5 Arab…       6621 CL_kha             11 asm    1971 1.00e0
 5 Andorra                 6 Arab…       6621 CL_kha             11 and    1971 1.00e0
 6 Angola                  7 Arab…       6621 CL_kha             11 ago    1971 2.90e3
 7 Antigua an…             8 Arab…       6621 CL_kha             11 atg    1971 5.80e0
 8 Argentina               9 Arab…       6621 CL_kha             11 arg    1971 2.60e4
 9 Aruba                  22 Arab…       6621 CL_kha             11 abw    1971 2.00e0
10 Australia              10 Arab…       6621 CL_kha             11 aus    1971 4.10e4
# ... with 8,950 more rows

> summary(new)
[checked, not shown]

> summary(old)
[checked, not shown]

> all.equal(as.data.frame(old), as.data.frame(new), check.attributes = FALSE)
[1] TRUE
```
In this PR I have replaced L100.FAO_CL_kha with the `readr 1.3`-read version.

**Comment by bpbond** [comment]
## L100.IEA_en_bal_ctry_hist

For L100.IEA_en_bal_ctry_hist, this object doesn't exist in `gcamdata.compdata`. On the one hand, this is the lightly-changed proprietary IEA data, so I see the reasoning to exclude it; but on the other, there's no provision in the `gcamdata` oldnew test to skip objects that aren't in `gcamdata.compdata`, so the fact that it's missing causes an error when running `gcamdata` with the proprietary IEA data installed.

@pralitp What do you think? I'd prefer to include it here, rather than add logic to skip a comparison if missing over in `gcamdata`.

Note this also applies to:
* `L101.en_bal_EJ_ctry_Si_Fi_Yh_full` 
* `L101.en_bal_EJ_R_Si_Fi_Yh_full`
* `L111.RsrcCurves_EJ_R_Ffos`
* `L118.out_EJ_R_elec_hydro_Yfut`
* `L121.in_EJ_R_TPES_crude_Yh`
* `L121.in_EJ_R_TPES_unoil_Yh`

**Comment by bpbond** [comment]
## L100.IMAGE_an_Feedfrac_ctry_C_Sys_Fd_Y

This data frame has also been replaced. The new version (as read by `readr` 1.3) is numerically identical:

```R
> old <- COMPDATA$L100.IMAGE_an_Feedfrac_ctry_C_Sys_Fd_Y
> new <- readr::read_csv("outputs/L100.IMAGE_an_Feedfrac_ctry_C_Sys_Fd_Y.csv", comment="#")

> summary(old)
  commodity            system             input               iso           
 Length:300800      Length:300800      Length:300800      Length:300800     
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
 IMAGE_region_ID      year          value          
 Min.   : 1.00   Min.   :1971   Min.   :0.0000000  
 1st Qu.: 8.00   1st Qu.:1981   1st Qu.:0.0004787  
 Median :11.00   Median :1990   Median :0.0530247  
 Mean   :12.16   Mean   :1990   Mean   :0.2500000  
 3rd Qu.:17.00   3rd Qu.:2000   3rd Qu.:0.4500000  
 Max.   :24.00   Max.   :2010   Max.   :1.0000000  

> summary(new)
  commodity            system             input               iso           
 Length:300800      Length:300800      Length:300800      Length:300800     
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
 IMAGE_region_ID      year          value          
 Min.   : 1.00   Min.   :1971   Min.   :0.0000000  
 1st Qu.: 8.00   1st Qu.:1981   1st Qu.:0.0004787  
 Median :11.00   Median :1990   Median :0.0530247  
 Mean   :12.16   Mean   :1990   Mean   :0.2500000  
 3rd Qu.:17.00   3rd Qu.:2000   3rd Qu.:0.4500000  
 Max.   :24.00   Max.   :2010   Max.   :1.0000000  

> all.equal(as.data.frame(old), as.data.frame(new), check.attributes = FALSE)
[1] TRUE
```

**Comment by bpbond** [comment]
## L100.IMAGE_an_Prodmixfrac_ctry_C_Y

Same story for L100.IMAGE_an_Prodmixfrac_ctry_C_Y, which has been replaced in this PR:

```R
> old <- COMPDATA$L100.IMAGE_an_Prodmixfrac_ctry_C_Y
> new <- readr::read_csv("outputs/L100.IMAGE_an_Prodmixfrac_ctry_C_Y.csv", comment = "#")

> summary(old)
  commodity             iso            IMAGE_region_ID      year     
 Length:47000       Length:47000       Min.   : 1.00   Min.   :1971  
 Class :character   Class :character   1st Qu.: 8.00   1st Qu.:1981  
 Mode  :character   Mode  :character   Median :11.00   Median :1990  
                                       Mean   :12.16   Mean   :1990  
                                       3rd Qu.:17.00   3rd Qu.:2000  
                                       Max.   :24.00   Max.   :2010  
     value       
 Min.   :0.0146  
 1st Qu.:0.5102  
 Median :1.0000  
 Mean   :0.7826  
 3rd Qu.:1.0000  
 Max.   :1.0000  

> summary(new)
  commodity             iso            IMAGE_region_ID      year     
 Length:47000       Length:47000       Min.   : 1.00   Min.   :1971  
 Class :character   Class :character   1st Qu.: 8.00   1st Qu.:1981  
 Mode  :character   Mode  :character   Median :11.00   Median :1990  
                                       Mean   :12.16   Mean   :1990  
                                       3rd Qu.:17.00   3rd Qu.:2000  
                                       Max.   :24.00   Max.   :2010  
     value       
 Min.   :0.0146  
 1st Qu.:0.5102  
 Median :1.0000  
 Mean   :0.7826  
 3rd Qu.:1.0000  
 Max.   :1.0000  

> all.equal(as.data.frame(old), as.data.frame(new), check.attributes=FALSE)
[1] TRUE
`

**Comment by bpbond** [comment]
## L100.Pop_thous_SSP_ctry_Yfut

I accidentally deleted the R session transcript for this one, but it was numerically identical, just had type differences caused by the new `readr`. Replaced in this PR.

**Comment by bpbond** [comment]
## L101.Pop_thous_Scen_R_Yfut

```$
> old <- COMPDATA$L101.Pop_thous_Scen_R_Yfut
> new <- readr::read_csv("outputs/L101.Pop_thous_Scen_R_Yfut.csv", comment = "#")
> all.equal(as.data.frame(old), as.data.frame(new), check.attributes=FALSE)
[1] TRUE
```

**Comment by bpbond** [comment]
## L107.an_Prod_Mt_R_C_Sys_Fd_Y

```R
> old <- COMPDATA$L107.an_Prod_Mt_R_C_Sys_Fd_Y
> new <- readr::read_csv("outputs/L107.an_Prod_Mt_R_C_Sys_Fd_Y.csv", comment="#")
> all.equal(as.data.frame(old), as.data.frame(new), check.attributes=FALSE)
[1] TRUE
```

**Comment by bpbond** [comment]
## L112.ghg_tg_R_en_S_F_Yh

```R
> old <- COMPDATA$L112.ghg_tg_R_en_S_F_Yh
> new <- readr::read_csv("outputs/L112.ghg_tg_R_en_S_F_Yh.csv", comment="#")
> all.equal(as.data.frame(old), as.data.frame(new), check.attributes=FALSE)
[1] TRUE
```

**Comment by bpbond** [comment]
Checked that all the following were the same numerically and replaced:
* `L1233.shrwt_R_elec_cool_Yf`
* `L131.nonco2_tg_R_prc_S_S_Yh`
* `L132.water_km3_ctry_ind_Yh`
* `L132.water_km3_R_ind_Yh`
* `L141.hfc_R_S_T_Yh`
* `L142.pfc_R_S_T_Yh`
* `L143.HDDCDD_scen_ctry_Y`
* `L143.HDDCDD_scen_R_Y`
* `L143.HDDCDD_scen_RG3_Y`
* `L143.HDDCDD_scen_state`
* `L154.cost_usdvkm_R_trn_m_sz_tech_F_Y`
* `L154.intensity_MJvkm_R_trn_m_sz_tech_F_Y`
* `L154.loadfactor_R_trn_m_sz_tech_F_Y`

**Comment by bpbond** [comment]
The following files had all-`NA` columns, which was being read as a character in one version of `readr` and logical in another. They were otherwise identical.

* `L2012.AgSupplySector`
* `L2012.AgSupplySubsector`
* `L202.SubsectorAll_an`
* `L202.SubsectorAll_in`
* `L202.Supplysector_an`
* `L202.Supplysector_in`
* `L203.SubsectorAll_demand`
* `L203.SubsectorLogit`
* `L203.Supplysector_demand`
* `L203.Supplysector`
* `L212.AgSupplySector`
* `L212.AgSupplySubsector`
* `L221.LN0_Logit`
* `L221.LN1_ValueLogit`
* `L221.SubsectorLogit_en`
* `L221.Supplysector_en`
* `L222.LN1_Logit_prot`
* `L222.LN2_Logit`
* `L222.Supplysector_en_USA`
* `L223.SubsectorLogit_elec_USA`
* `L223.SubsectorLogit_elec`
* `L223.Supplysector_elec_USA`
* `L223.Supplysector_elec`
* `L2231.LN1_Logit_prot`
* `L2231.LN3_Logit`
* `L2231.LN3_NodeCarbon`
* `L2231.LN3_NoEmissCarbon`
* `L2232.SubsectorLogit_elec_FERC`
* `L2232.SubsectorLogit_USAelec`
* `L2232.Supplysector_elec_FERC`
* `L2232.Supplysector_USAelec`
* `L2233.SubsectorLogit_elec_cool`
* `L2233.Supplysector_elec_cool`
* `L224.SubsectorLogit_heat`
* `L224.Supplysector_heat`
* `L225.SubsectorLogit_h2`
* `L225.Supplysector_h2`
* `L226.SubsectorLogit_electd_USA`
* `L226.SubsectorLogit_en_USA`
* `L226.SubsectorLogit_en`
* `L226.Supplysector_electd_USA`
* `L226.Supplysector_en_USA`
* `L226.Supplysector_en`
* `L231.SubsectorLogit_urb_ind`
* `L231.Supplysector_urb_ind`
* `L231.UnlimitRsrc`
* `L232.SubsectorLogit_ind_USA`
* `L232.SubsectorLogit_ind`
* `L232.Supplysector_ind_USA`
* `L232.Supplysector_ind`
* `L2321.SubsectorLogit_cement_USA`
* `L2321.SubsectorLogit_cement`
* `L2321.Supplysector_cement_USA`
* `L2321.Supplysector_cement`
* `L2322.SubsectorLogit_Fert_USA`
* `L2322.SubsectorLogit_Fert`
* `L2322.SubsectorLogit_USAFert`
* `L2322.Supplysector_Fert_USA`
* `L2322.Supplysector_Fert`
* `L242.SubsectorLogit_bld`
* `L242.Supplysector_bld`
* `L243.SubsectorLogit_Bio`
* `L243.Supplysector_Bio`
* `L244.SubsectorLogit_bld_gcamusa`
* `L244.SubsectorLogit_bld`
* `L244.Supplysector_bld_gcamusa`
* `L244.Supplysector_bld`
* `L245.SubsectorLogit`
* `L245.Supplysector`
* `L252.SubsectorLogit_trn`
* `L252.Supplysector_trn`
* `L261.SubsectorLogit_C_USA`
* `L261.SubsectorLogit_C`
* `L261.SubsectorShrwtFllt_C`

**Comment by bpbond** [comment]
A few more that just varied by a logical/character column, confirmed identical otherwise:
* `L144.shell_eff_R_Y`
* `L222.GlobalTechShrwt_en`
* `L222.GlobalTechShrwt_en_USA`
* `L254.BaseService_trn`

**Comment by bpbond** [comment]
Down to only a few problems:
```
test_oldnew.R:108: failure: matches old data system output
round_df(olddata) not equivalent to round_df(newdata).
Incompatible type for column `logit.type`: x character, y logical
L2242.LN4_Logit.csv doesn't match

test_oldnew.R:108: failure: matches old data system output
round_df(olddata) not equivalent to round_df(newdata).
Rows in x but not y: 647. Rows in y but not x: 647. 
L244.GlobalTechIntGainOutputRatio.csv doesn't match

test_oldnew.R:108: failure: matches old data system output
round_df(olddata) not equivalent to round_df(newdata).
Rows in x but not y: 569. Rows in y but not x: 569. 
L254.StubTechCalInput_passthru.csv doesn't match

test_oldnew.R:108: failure: matches old data system output
round_df(olddata) not equivalent to round_df(newdata).
Rows in x but not y: 28815, 28807, 28799, 28759, 28743, 27947, 18017, 18033, 16198, 16088, 16068[...]. Rows in y but not x: 28815, 28807, 28799, 26826, 18033, 18017, 17993, 16208, 16118, 16098, 16088[...]. 
L254.StubTranTechLoadFactor.csv doesn't match
```

But these will wait for 2019! 🎉

**Comment by bpbond** [comment]
## L2242.LN4_Logit

Had a logical/character NA column issue. Verified identical otherwise.

## L244.GlobalTechIntGainOutputRatio

Two issues: the year column was integer (old) versus numeric (new), and there was a tiny numeric difference in one field.
```R
> print(all.equal(old, new, check.attributes = FALSE))
[1] "Component “internal.gains.output.ratio”: Mean relative difference: 0.0001891432"
[1] "Incompatible type for column `year`: x integer, y numeric"

> summary((new$internal.gains.output.ratio-old$internal.gains.output.ratio)/old$internal.gains.output.ratio)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
0.00000 0.00000 0.00000 0.00000 0.00000 0.00019      66 
```
I assume this is small enough we can shift to the new values without problem but **should be checked**.

## L254.StubTechCalInput_passthru

Some integer/year mismatches, and a tiny difference in one field:
```R
> all.equal(old$calibrated.value, new$calibrated.value)
[1] "Mean relative difference: 2.081612e-08"

> summary((new$calibrated.value-old$calibrated.value)/old$calibrated.value)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
      0       0       0       0       0       0       1 
```

## L254.StubTranTechLoadFactor

A integer/numeric year mismatch, and the loadfactor field had small differences:
```R
> all.equal(old$loadFactor, new$loadFactor)
[1] "Mean relative difference: 0.003656598"

> summary((new$loadFactor-old$loadFactor)/old$loadFactor)
      Min.    1st Qu.     Median       Mean    3rd Qu.       Max. 
-8.850e-03  0.000e+00  0.000e+00 -8.460e-07  0.000e+00  8.197e-03 
```

Again, this should be fine but **need to check**.

**Comment by bpbond** [comment]
Getting rid of `protect_float` in https://github.com/JGCRI/gcamdata/pull/1073/commits/a73c03104cc285af1bac01d584f2566556aee70e triggered a new set of inconsistencies, again all due to integer/numeric inconsistencies:
* `L100.IEA_en_bal_ctry_hist`
* `L100.Pop_thous_SSP_ctry_Yfut`
* `L102.CO2_Mt_R_F_Yh`
* `L102.gdp_mil90usd_GCAM3_ctry_Y`
* `L105.an_Prod_Mt_ctry_C_Y`
* `L105.an_Prod_Mt_R_C_Y`
* `L111.nonghg_tg_R_en_S_F_Yh`
* `L122.LC_bm2_R_HarvCropLand_C_Yh_GLU`
* `L123.LC_bm2_R_MgdFor_Yh_GLU`
* `L124.LC_bm2_R_Grass_Yh_GLU_adj`
* `L124.LC_bm2_R_Shrub_Yh_GLU_adj`
* `L125.LC_bm2_R_GLU`
* `L161.ag_irrHA_frac_R_C_GLU`
* `L162.ag_YieldRate_R_C_Y_GLU_irr`
* `L171.LC_bm2_R_rfdHarvCropLand_C_Yh_GLU`
* `L181.LC_bm2_R_C_Yh_GLU_irr_level`
* `L2012.AgYield_bio_ref`
* `L2052.AgProdChange_irr_high`
* `L2052.AgProdChange_irr_ssp4`
* `L2231.LN3_HistUnmgdAllocation_noprot`

**Review by pralitp — APPROVED** [review]

**Pull request merged**
